# Generated by Django 3.1.6 on 2021-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210208_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-established_date',)},
        ),
        migrations.AddField(
            model_name='board',
            name='visit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
