# Generated by Django 3.1.6 on 2021-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210208_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='established_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
